/*
 * Autogenerated file! Do not manually edit this file. This version is regenerated
 * any time the publish task is run, or when this file is deleted.
 */

const char* WPILibVersion = "424242.2017.1.1-rc-2-20170101104307-3-g182f572-dirty";