package edu.wpi.first.wpilibj.util;

/*
 * Autogenerated file! Do not manually edit this file. This version is regenerated
 * any time the publish task is run, or when this file is deleted.
 */

public final class WPILibVersion {
  public static final String Version = "424242.2017.1.1-beta-3-20161216134836-27-g6dffc85-dirty";
}